# Generated by Django 5.2.16 on 2026-07-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Time spent on this question in seconds')),
            ],
            options={
                'verbose_name': 'answer attempt',
                'verbose_name_plural': 'answer attempts',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Area name (e.g., Reglamentacion, Tecnica)', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Category code: CD, CA, CE, XQ', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Category name (e.g., Novicio, General, Superior)', max_length=50)),
                ('exam_size', models.IntegerField(help_text='Total number of questions in an exam for this category')),
                ('reglamento_count', models.IntegerField(help_text='Number of questions from Reglamento section')),
                ('tecnica_count', models.IntegerField(help_text='Number of questions from Tecnica section')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Question text')),
                ('option_a', models.CharField(help_text='Option A', max_length=500)),
                ('option_b', models.CharField(help_text='Option B', max_length=500)),
                ('option_c', models.CharField(help_text='Option C', max_length=500)),
                ('option_d', models.CharField(help_text='Option D', max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct answer (A, B, C, or D)', max_length=1)),
                ('explanation', models.TextField(blank=True, default='', help_text='Explanation for the correct answer (optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active and can appear in exams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['category', 'area', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Topic name', max_length=100)),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('exam', 'Examen'), ('training', 'Entrenamiento')], help_text='Exam mode: exam (timed, graded) or training (with feedback)', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, help_text='Score as percentage (0-100)', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.category')),
            ],
            options={
                'verbose_name': 'exam attempt',
                'verbose_name_plural': 'exam attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
