# Generated by Django 5.2.16 on 2026-07-27 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='exam_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt'),
        ),
        migrations.AddField(
            model_name='question',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.area'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.category'),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='exams.question'),
        ),
        migrations.AddField(
            model_name='tema',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='exams.area'),
        ),
        migrations.AddField(
            model_name='tema',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='exams.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.tema'),
        ),
        migrations.AlterUniqueTogether(
            name='answerattempt',
            unique_together={('exam_attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('name', 'area', 'category')},
        ),
    ]
